version: '3.9'

services:
  db:
    build: ./db
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=ACAB_DB
    volumes:
      - ./data:/data
  api:
    build: ./api
    container_name: api
    restart: always
    environment:
      - PORT=8000
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=ACAB_DB
      - DB_HOST=db
    depends_on:
      - db
  web:
    build: ./web
    container_name: web
    restart: always
    ports:
      - 5000:5000
    environment:
      - API_HOST=http://api:8000
    depends_on:
      - api
